### ISSUE TITLE
nuniroot not converging for F-distributions with a large non-centrallity parameter

### ISSUE THREAD

**Issue by juliancg24** [johnnyzhz/WebPower#1]
Take for example this setup for estimating a two-sided omnibus effect in a 3-arm clustered design:

``` r
n     = 2452
J     = 101
icc   = 0.04
power = 0.8
alpha = 0.05

p.body <- quote({
  df1 <- 2
  df2 <- J - 3
  lambda3 <- J * f^2/(icc + (1 - icc)/n)
  f0 <- qf(1 - alpha, df1, df2)
  1 - pf(f0, df1, df2, lambda3)
})

nuniroot(function(f) eval(p.body) - power, c(1e+07, 1e+07))
```
Error is not so informative:

```
Error in nuniroot(function(f) eval(p.body) - power, c(1e+07, 1e+07)) : 
  The specified parameters do not yield valid results.
```

From the `pf` R base documentation: 

> The code for non-zero ncp is principally intended to be used for moderate values of ncp: it will not be highly accurate, especially in the tails, for large values.

In the example above `lambda3 = 2.451744e+17` in the upper-tail of the default interval that `nuniroot` uses. When changing the upper limit to `1e+05` the distribution behaves better and results are as expected. Other functions such as `wp.effect.CRT3arm` should allow to edit the interval of `nunitroot` manually.

**Comment by johnnyzhz** [comment]
Thanks for the feedback. I couldn't reproduce the error. What's the sample size n in your example?

**Comment by juliancg24** [comment]
Sorry `n = 2452` I edited the error output above too.

**Comment by johnnyzhz** [comment]
Thank you, @juliancg24!

Sorry for the late reply. Yes, I was able to reproduce the error. I will make the change in the next release of the package. It will take some time since now the interval was hard-programmed in the functions.

**Comment by johnnyzhz** [comment]
I temporarily fixed the problem by allowing one to specify an interval when using the related functions. But the fundamental issue is that the function under evaluation is not monotone. I still need to fix out an way to solve this.
